# Generated by Django 4.1.1 on 2022-10-08 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_temperature', models.CharField(max_length=32)),
                ('data_heartBeat', models.CharField(max_length=32)),
                ('data_bloodPressure', models.CharField(max_length=32)),
                ('remark', models.TextField(max_length=8192)),
                ('saveDate', models.DateTimeField(default=datetime.datetime(2022, 10, 8, 19, 58, 57, 858516), verbose_name='date punished')),
            ],
        ),
    ]
