# Generated by Django 4.1.1 on 2022-10-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_healthdata_data_bloodpressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='data_bloodPressure',
            field=models.FloatField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='data_heartBeat',
            field=models.FloatField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='data_temperature',
            field=models.FloatField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='remark',
            field=models.TextField(blank=True, max_length=8192),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='saveDate',
            field=models.DateTimeField(default='2022-10-21 14:13:52', verbose_name='date punished'),
        ),
    ]
