# Generated by Django 4.1.1 on 2022-10-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_healthdata_data_bloodpressure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthdata',
            old_name='data_bloodPressure',
            new_name='data_bloodPressure_dia',
        ),
        migrations.AddField(
            model_name='healthdata',
            name='data_bloodPressure_sys',
            field=models.FloatField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='saveDate',
            field=models.DateTimeField(default='2022-10-25 11:15:28', verbose_name='date punished'),
        ),
    ]
