# Generated by Django 4.1.1 on 2022-11-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_data_bloodpressure_healthdata_data_bloodpressure_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='data_spo2',
            field=models.FloatField(default=10, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='data_bloodPressure_dia',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='data_bloodPressure_sys',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='data_heartBeat',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='data_temperature',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='saveDate',
            field=models.DateTimeField(default='2022-11-01 10:03:37', verbose_name='date punished'),
        ),
    ]
